### PR TITLE
Fix Docker & Odin import

### LINKED ISSUE #30: Make Odin XML import work again
A user mentioned on the foodcoops.net support mailing list that the Odin / DNB sharedlists supplier hadn't been updating.
Most probably this is because the format sent by mail has changed. Upto 2019, the XML file was sent as a direct attachment, since 2020 the XML file was packed in a ZIP file (after Odin took over De Nieuwe Band).

Importer: https://github.com/foodcoops/sharedlists/blob/master/app/lib/article_import/dnb_xml.rb

### PR DESCRIPTION
**Pull request by wvengen**
Fixes #30.
Needed to change some things to get sharedlists actually running again.

Hope it's ok to put this in one PR (I spent the time I had), each commit should be self-explanatory.
Will merge if no reply in a couple of days, since there is an immediate user need for the Odin import _and_ currently sharedlists wouldn't even run on development.

### CODE REVIEW

**Comment by wvengen** [comment]
I'm a bit puzzled by which version is runining on foodcoops.net - is it this main repository, or do we run another fork? If elsewhere, I think it would be good to get this version up-to-date with whatever we are running in foodcoops.net production.
@kidhab do you have any background on this?

**Comment by kidhab** [comment]
foodcoops.net uses my [fork](https://github.com/foodcoops/foodcoops.net/tree/master/Ansible#roles-overview) which basically uses bootstrap for the interface and updates all dependencies. I recently also [fixed](https://github.com/kidhab/sharedlists/commit/44f6f5ef486bf245476e70e532835e6536729220) the Docker build process.

**Comment by wvengen** [comment]
Ah, great!
Would you be open to use this repo again for foodcoops.net? You should have access to it now.

**Comment by wvengen** [comment]
Thank you, @kidhab!
Yes, Odin should still be sending updates, but they aren't recognized now (as far as my knowledge reaches). After this change, the format should become _Odin / Nieuwe Band (ZIP)_ (instead of _Odin / Nieuwe Band (XML)_).

**Pull request merged**
